version: '3.1'

services:
  db:
      image: mysql:8.0
      privileged: true
      ports:
        - "3306:3306"
      environment:
        MYSQL_USER: root
        MYSQL_PASSWORD: sc6h9mk5
        MYSQL_DB: horns_hooves_db
  adminer:
      image: adminer:4.7.8-standalone
      restart: always
      ports:
        - 8080:8080
      depends_on:
        - db
